version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/react/react-hello-world   # Destination directory on the EC2 instance

hooks:
  ApplicationStart:
    - location: scripts/after_deploy.sh
      timeout: 300
